export interface ICookingBookValues{
    ingrdients: string,
    recipe: string,
    filter: string,
    name: string,
    description: string,
    hoTo: string,
    menuType: string,
    amount: string,
    unit: string,
    addIngredient: string,
    addRecipe: string,
    deleteRecipe: string,
    saveRecipe: string,
    cancel: string,
    updateRecipe: string,
    unitLiter: string,
    unitMilliliters: string,
    unitKilo: string,
    unitGram: string,
    unitTablespoon: string,
    unitTeaspoon: string,
    unitPiece: string
    recipePasta: string,
    recipeSoup: string,
    recipeMeat: string,
    recipePastries: string
    select: string
    pageTitleAdd: string
    pageTitleView: string
    pageTitleEdit: string
}